pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.createmod.net' }
        maven { url = 'https://mvn.devos.one/snapshots' }
        maven { url = 'https://maven.blamejared.com' }
    }
}

rootProject.name = 'Create-Airburst'
